export const books = [
  "Gunslinger by Ed Dorn",
  "The Invention of Morel by Adolfo Bioy Casares",
  "The Hour of the Star by Clarice Lispector",
  "The Street of Crocodiles by Bruno Schulz",
  "Motorman by David Ohle",
  "Fiskadoro by Denis Johnson",
  "The Orange Eats Creeps by Grace Krilanovich",
  "A Pale View of Hills by Kazuo Ishiguro",
  "Winter in the Blood by James Welch",
  "An Episode in the Life of a Landscape Painter by César Aira",
  "The Seven Madmen by Roberto Arlt",
  "Speedboat by Renata Adler",
  "Machine by Susan Steinberg",
  "The Day of the Locust by Nathanael West",
  "Pierrot Mon Ami by Raymond Queneau",
  "McGlue by Ottessa Moshfegh",
  "The Old Man and the Bench by Urs Allemann",
  "Binsteads Safari by Rachel Ingalls",
  "Between Dog and Wolf by Sasha Sokolov",
];

export const votes = [
  [
    "Gunslinger by Ed Dorn",
    "The Invention of Morel by Adolfo Bioy Casares",
    "The Hour of the Star by Clarice Lispector",
    "The Street of Crocodiles by Bruno Schulz",
    "Motorman by David Ohle",
    "Fiskadoro by Denis Johnson",
    "The Orange Eats Creeps by Grace Krilanovich",
    "A Pale View of Hills by Kazuo Ishiguro",
    "Winter in the Blood by James Welch",
    "An Episode in the Life of a Landscape Painter by César Aira",
    "The Seven Madmen by Roberto Arlt",
    "Speedboat by Renata Adler",
    "Machine by Susan Steinberg",
    "The Day of the Locust by Nathanael West",
    "Pierrot Mon Ami by Raymond Queneau",
    "McGlue by Ottessa Moshfegh",
    "The Old Man and the Bench by Urs Allemann",
    "Binsteads Safari by Rachel Ingalls",
    "Between Dog and Wolf by Sasha Sokolov",
  ],
  [
    "The Street of Crocodiles by Bruno Schulz",
    "Binsteads Safari by Rachel Ingalls",
    "The Day of the Locust by Nathanael West",
    "Pierrot Mon Ami by Raymond Queneau",
    "Gunslinger by Ed Dorn",
    "A Pale View of Hills by Kazuo Ishiguro",
    "Between Dog and Wolf by Sasha Sokolov",
    "Machine by Susan Steinberg",
    "Motorman by David Ohle",
    "McGlue by Ottessa Moshfegh",
    "Fiskadoro by Denis Johnson",
    "An Episode in the Life of a Landscape Painter by César Aira",
    "Winter in the Blood by James Welch",
    "The Orange Eats Creeps by Grace Krilanovich",
    "The Seven Madmen by Roberto Arlt",
    "Speedboat by Renata Adler",
    "The Hour of the Star by Clarice Lispector",
    "The Old Man and the Bench by Urs Allemann",
  ],
  [
    "The Seven Madmen by Roberto Arlt",
    "Between Dog and Wolf by Sasha Sokolov",
    "Pierrot Mon Ami by Raymond Queneau",
    "The Hour of the Star by Clarice Lispector",
    "The Street of Crocodiles by Bruno Schulz",
    "Motorman by David Ohle",
    "Binsteads Safari by Rachel Ingalls",
    "Speedboat by Renata Adler",
    "Fiskadoro by Denis Johnson",
    "McGlue by Ottessa Moshfegh",
    "The Day of the Locust by Nathanael West",
    "An Episode in the Life of a Landscape Painter by César Aira",
    "The Invention of Morel by Adolfo Bioy Casares",
    "Winter in the Blood by James Welch",
    "A Pale View of Hills by Kazuo Ishiguro",
    "Gunslinger by Ed Dorn",
    "The Old Man and the Bench by Urs Allemann",
    "Machine by Susan Steinberg",
    "The Orange Eats Creeps by Grace Krilanovich",
  ],
  [
    "Between Dog and Wolf by Sasha Sokolov",
    "Gunslinger by Ed Dorn",
    "The Seven Madmen by Roberto Arlt",
    "Binsteads Safari by Rachel Ingalls",
    "The Street of Crocodiles by Bruno Schulz",
    "Motorman by David Ohle",
    "Fiskadoro by Denis Johnson",
    "An Episode in the Life of a Landscape Painter by César Aira",
    "McGlue by Ottessa Moshfegh",
    "Pierrot Mon Ami by Raymond Queneau",
    "The Invention of Morel by Adolfo Bioy Casares",
    "Winter in the Blood by James Welch",
    "Speedboat by Renata Adler",
    "Machine by Susan Steinberg",
    "The Orange Eats Creeps by Grace Krilanovich",
    "The Old Man and the Bench by Urs Allemann",
    "The Day of the Locust by Nathanael West",
    "The Hour of the Star by Clarice Lispector",
    "A Pale View of Hills by Kazuo Ishiguro",
  ],
  [
    "The Hour of the Star by Clarice Lispector",
    "Speedboat by Renata Adler",
    "Between Dog and Wolf by Sasha Sokolov",
    "Pierrot Mon Ami by Raymond Queneau",
    "The Invention of Morel by Adolfo Bioy Casares",
    "Gunslinger by Ed Dorn",
    "Binsteads Safari by Rachel Ingalls",
    "The Seven Madmen by Roberto Arlt",
    "Fiskadoro by Denis Johnson",
    "Motorman by David Ohle",
    "The Old Man and the Bench by Urs Allemann",
    "McGlue by Ottessa Moshfegh",
    "The Orange Eats Creeps by Grace Krilanovich",
    "Machine by Susan Steinberg",
    "The Day of the Locust by Nathanael West",
    "The Street of Crocodiles by Bruno Schulz",
    "A Pale View of Hills by Kazuo Ishiguro",
    "An Episode in the Life of a Landscape Painter by César Aira",
    "Winter in the Blood by James Welch",
  ],
  [
    "The Day of the Locust by Nathanael West",
    "Fiskadoro by Denis Johnson",
    "The Hour of the Star by Clarice Lispector",
    "Speedboat by Renata Adler",
    "Gunslinger by Ed Dorn",
    "Pierrot Mon Ami by Raymond Queneau",
    "The Seven Madmen by Roberto Arlt",
    "The Invention of Morel by Adolfo Bioy Casares",
    "The Street of Crocodiles by Bruno Schulz",
    "An Episode in the Life of a Landscape Painter by César Aira",
    "Binsteads Safari by Rachel Ingalls",
    "Between Dog and Wolf by Sasha Sokolov",
    "McGlue by Ottessa Moshfegh",
    "The Old Man and the Bench by Urs Allemann",
    "The Orange Eats Creeps by Grace Krilanovich",
    "Winter in the Blood by James Welch",
    "Machine by Susan Steinberg",
    "A Pale View of Hills by Kazuo Ishiguro",
    "Motorman by David Ohle",
  ],
];
