export const books = [
  "Berg by Ann Quin",
  "Parable of the Sower by Octavia E. Butler",
  "The apple in the dark by Clarice Lispector",
  "Almanac of the Dead by Leslie Marmon Silko",
  "Praiseworthy by Alexis Wright",
  "I Who Have Never Known Men by Jacqueline Harpman",
];

export const votes = [
  [
    "Praiseworthy by Alexis Wright",
    "Almanac of the Dead by Leslie Marmon Silko",
    "Berg by Ann Quin",
    "The apple in the dark by Clarice Lispector",
    "I Who Have Never Known Men by Jacqueline Harpman",
    "Parable of the Sower by Octavia E. Butler",
  ],
  [
    "The apple in the dark by Clarice Lispector",
    "Parable of the Sower by Octavia E. Butler",
    "Berg by Ann Quin",
    "I Who Have Never Known Men by Jacqueline Harpman",
    "Praiseworthy by Alexis Wright",
    "Almanac of the Dead by Leslie Marmon Silko",
  ],
  [
    "Berg by Ann Quin",
    "Almanac of the Dead by Leslie Marmon Silko",
    "Parable of the Sower by Octavia E. Butler",
    "I Who Have Never Known Men by Jacqueline Harpman",
    "The apple in the dark by Clarice Lispector",
    "Praiseworthy by Alexis Wright",
  ],
  [
    "Praiseworthy by Alexis Wright",
    "Parable of the Sower by Octavia E. Butler",
    "I Who Have Never Known Men by Jacqueline Harpman",
    "Almanac of the Dead by Leslie Marmon Silko",
    "Berg by Ann Quin",
    "The apple in the dark by Clarice Lispector",
  ],
  [
    "Berg by Ann Quin",
    "Praiseworthy by Alexis Wright",
    "The apple in the dark by Clarice Lispector",
    "Parable of the Sower by Octavia E. Butler",
    "Almanac of the Dead by Leslie Marmon Silko",
    "I Who Have Never Known Men by Jacqueline Harpman",
  ],
  [
    "The apple in the dark by Clarice Lispector",
    "Almanac of the Dead by Leslie Marmon Silko",
    "Berg by Ann Quin",
    "I Who Have Never Known Men by Jacqueline Harpman",
    "Parable of the Sower by Octavia E. Butler",
    "Praiseworthy by Alexis Wright",
  ],
  [
    "The apple in the dark by Clarice Lispector",
    "Berg by Ann Quin",
    "Almanac of the Dead by Leslie Marmon Silko",
    "I Who Have Never Known Men by Jacqueline Harpman",
    "Parable of the Sower by Octavia E. Butler",
    "Praiseworthy by Alexis Wright",
  ],
];
