export const books = [
  "On Heroes and Tombs by Ernesto Sabato",
  "A Naked Singularity by Sergio De La Pava",
  "The Invented Part by Rodrigo Fresán",
  "Life a Users Manual by Georges Perec",
  "A Glastonbury Romance by John Cowper Powys",
  "The Public Burning by Robert Coover",
  "Septology by Jon Fosse",
  "Chevengur by Andrei Platonov",
  "Wolf Solent by John Cowper Powys",
  "Mulligan Stew by Gilbert Sorrentino",
  "Miss MacIntosh, My Darling by Marguerite Young",
  "Ducks, Newburyport by Lucy Ellmann",
];

export const votes = [
  [
    "On Heroes and Tombs by Ernesto Sabato",
    "Miss MacIntosh, My Darling by Marguerite Young",
    "Wolf Solent by John Cowper Powys",
    "The Invented Part by Rodrigo Fresán",
    "A Naked Singularity by Sergio De La Pava",
    "Life a Users Manual by Georges Perec",
    "Ducks, Newburyport by Lucy Ellmann",
    "Mulligan Stew by Gilbert Sorrentino",
    "A Glastonbury Romance by John Cowper Powys",
    "Septology by Jon Fosse",
    "Chevengur by Andrei Platonov",
  ],
  [
    "On Heroes and Tombs by Ernesto Sabato",
    "A Naked Singularity by Sergio De La Pava",
    "The Invented Part by Rodrigo Fresán",
    "Life a Users Manual by Georges Perec",
    "A Glastonbury Romance by John Cowper Powys",
    "The Public Burning by Robert Coover",
    "Septology by Jon Fosse",
    "Chevengur by Andrei Platonov",
    "Wolf Solent by John Cowper Powys",
    "Mulligan Stew by Gilbert Sorrentino",
    "Miss MacIntosh, My Darling by Marguerite Young",
    "Ducks, Newburyport by Lucy Ellmann",
  ],
  [
    "On Heroes and Tombs by Ernesto Sabato",
    "The Public Burning by Robert Coover",
    "A Glastonbury Romance by John Cowper Powys",
    "The Invented Part by Rodrigo Fresán",
    "Miss MacIntosh, My Darling by Marguerite Young",
    "Chevengur by Andrei Platonov",
    "A Naked Singularity by Sergio De La Pava",
    "Mulligan Stew by Gilbert Sorrentino",
    "Wolf Solent by John Cowper Powys",
    "Life a Users Manual by Georges Perec",
    "Ducks, Newburyport by Lucy Ellmann",
    "Septology by Jon Fosse",
  ],
  [
    "On Heroes and Tombs by Ernesto Sabato",
    "The Public Burning by Robert Coover",
    "Life a Users Manual by Georges Perec",
    "A Naked Singularity by Sergio De La Pava",
    "Septology by Jon Fosse",
    "A Glastonbury Romance by John Cowper Powys",
    "The Invented Part by Rodrigo Fresán",
    "Mulligan Stew by Gilbert Sorrentino",
    "Miss MacIntosh, My Darling by Marguerite Young",
    "Ducks, Newburyport by Lucy Ellmann",
    "Wolf Solent by John Cowper Powys",
    "Chevengur by Andrei Platonov",
  ],
  [
    "Septology by Jon Fosse",
    "A Naked Singularity by Sergio De La Pava",
    "Wolf Solent by John Cowper Powys",
    "On Heroes and Tombs by Ernesto Sabato",
    "A Glastonbury Romance by John Cowper Powys",
    "Mulligan Stew by Gilbert Sorrentino",
    "The Public Burning by Robert Coover",
    "The Invented Part by Rodrigo Fresán",
    "Chevengur by Andrei Platonov",
    "Ducks, Newburyport by Lucy Ellmann",
    "Miss MacIntosh, My Darling by Marguerite Young",
    "Life a Users Manual by Georges Perec",
  ],
  [
    "Septology by Jon Fosse",
    "Chevengur by Andrei Platonov",
    "Mulligan Stew by Gilbert Sorrentino",
    "Wolf Solent by John Cowper Powys",
    "The Invented Part by Rodrigo Fresán",
    "On Heroes and Tombs by Ernesto Sabato",
    "A Glastonbury Romance by John Cowper Powys",
    "The Public Burning by Robert Coover",
    "Miss MacIntosh, My Darling by Marguerite Young",
    "Life a Users Manual by Georges Perec",
    "A Naked Singularity by Sergio De La Pava",
    "Ducks, Newburyport by Lucy Ellmann",
  ],
  [
    "Septology by Jon Fosse",
    "Chevengur by Andrei Platonov",
    "Wolf Solent by John Cowper Powys",
    "A Naked Singularity by Sergio De La Pava",
    "On Heroes and Tombs by Ernesto Sabato",
    "A Glastonbury Romance by John Cowper Powys",
    "Ducks, Newburyport by Lucy Ellmann",
    "The Invented Part by Rodrigo Fresán",
    "Miss MacIntosh, My Darling by Marguerite Young",
    "The Public Burning by Robert Coover",
    "Mulligan Stew by Gilbert Sorrentino",
    "Life a Users Manual by Georges Perec",
  ],
];
